name: run-tests

on:
  push:
    branches:
      - main

jobs:
  run-ALL-the-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Install and Run
        run: |
          npm install
          npm run test
          rm -rf node_modules
